#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum Register {
    X0,
    X1,
    X2,
    X3,
    X4,
    X5,
    X6,
    X7,
    X8,
    X9,
    X10,
    X11,
    X12,
    X13,
    X14,
    X15,
    X16,
    X17,
    X18,
    X19,
    X20,
    X21,
    X22,
    X23,
    X24,
    X25,
    X26,
    X27,
    X28,
    X29,
    X30,
    X31,
    PC,
}

impl Default for Register {
    fn default() -> Self {
        Register::X0
    }
}

#[derive(Debug, Copy, Clone)]
pub enum ABI {
    Zero,
    RA,
    SP,
    GP,
    TP,
    T0,
    T1,
    T2,
    S0,
    FP,
    S1,
    A0,
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    S2,
    S3,
    S4,
    S5,
    S6,
    S7,
    S8,
    S9,
    S10,
    S11,
    T3,
    T4,
    T5,
    T6,
}

impl ABI {
    pub fn to_r(&self) -> Register {
        match self {
            Self::Zero => Register::X0,
            Self::RA => Register::X1,
            Self::SP => Register::X2,
            Self::GP => Register::X3,
            Self::TP => Register::X4,
            Self::T0 => Register::X5,
            Self::T1 => Register::X6,
            Self::T2 => Register::X7,
            Self::S0 => Register::X8,
            Self::FP => Register::X8,
            Self::S1 => Register::X9,
            Self::A0 => Register::X10,
            Self::A1 => Register::X11,
            Self::A2 => Register::X12,
            Self::A3 => Register::X13,
            Self::A4 => Register::X14,
            Self::A5 => Register::X15,
            Self::A6 => Register::X16,
            Self::A7 => Register::X17,
            Self::S2 => Register::X18,
            Self::S3 => Register::X19,
            Self::S4 => Register::X20,
            Self::S5 => Register::X21,
            Self::S6 => Register::X22,
            Self::S7 => Register::X23,
            Self::S8 => Register::X24,
            Self::S9 => Register::X25,
            Self::S10 => Register::X26,
            Self::S11 => Register::X27,
            Self::T3 => Register::X28,
            Self::T4 => Register::X29,
            Self::T5 => Register::X30,
            Self::T6 => Register::X31,
        }
    }
}
